// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyArithmeiticBoard: typeof import('./src/components/SyArithmeiticBoard/index.vue')['default']
    SyArithmeticBoard: typeof import('./src/components/SyArithmeticBoard/index.vue')['default']
    SyArithmeticCard: typeof import('./src/components/SyArithmeticCard/index.vue')['default']
    SyKeyboard: typeof import('./src/components/SyKeyboard.vue')['default']
  }
}
