// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArithmeiticBoard: typeof import('./src/components/ArithmeiticBoard/index.vue')['default']
    ArithmeticCard: typeof import('./src/components/ArithmeticCard/index.vue')['default']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyArithmeiticBoard: typeof import('./src/components/SyArithmeiticBoard/index.vue')['default']
    SyArithmeticCard: typeof import('./src/components/SyArithmeticCard/index.vue')['default']
    SyInputBoard: typeof import('./src/components/ArithmeiticBoard/SyInputBoard.vue')['default']
    SyInputCard: typeof import('./src/components/SyInputCard/index.vue')['default']
    SyKeyboard: typeof import('./src/components/SyKeyboard.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
